music4u/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^albums/', include('musicalbums.urls', namespace='musicalbums'))
]

musicalbums/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.details, name='details')
]

musicalbums/models.py
from __future__ import unicode_literals

from django.db import models


class Album(models.Model):
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    minutes = models.IntegerField()
    seconds = models.IntegerField()

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

musicalbums/views.py
from django.shortcuts import render
from django.http import HttpResponse

from musicalbums.models import Album



def index(request):
    return render(request, 'musicalbums/index.html', {'albums': Album.objects.all()})


def details(request, pk):
    return HttpResponse('<h1>Details for %(pk)s<h1>' % {'pk': pk})

musicalbums/templates/musicalbums/base.html
<!doctype html>
<html lang="en-ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block header %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">M4U</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Albums <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Songs</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Add Album</a></li>
                <li><a href="#">Login</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    {% endblock %}

    {% block main %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

musicalbums/templates/musicalbums/index.html
{% extends 'musicalbums/base.html' %}

{% block title %}Albums{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        {% for album in albums %}
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="{{ album.logo }}" alt="{{ album.name }}">
                <div class="caption">
                    <h3>{{ album.name }}</h3>
                    <p>{{ album.author }}</p>
                    <p><a href="{% url 'musicalbums:details' album.id %}" class="btn btn-primary" role="button">Details</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}